name: "Fastlane for Test Environment"

on:
  workflow_dispatch:

jobs:
  buildApp:
    name: "Build App"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install fastlane"
        run: "sudo gem install fastlane -NV"

      - name: "Run fastlane command"
        run:  "bundle exec fastlane launch_ci_build env:\"dev\""