name: "Fastlane for Test Environment"

on:
  workflow_dispatch:

jobs:
  buildApp:
    name: "Setup"
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "List files"
        run: "ls -la"

      - name: "Where am i?"
        run: "pwd"

      - name: "Install fastlane"
        run: "sudo gem install fastlane -NV"

      - name: "List files"
        run: "ls -la"

      - name: "Install Dependencies"
        run: "yarn install"

      - name: "List files"
        run: "ls -la"

      - name: "Run fastlane command"
        run:  "bundle exec fastlane ios ci_dev"