name: "Fastlane for Staging Environment"

on:
  workflow_dispatch:

jobs:
  buildiOSApp:
    name: "Build iOS App"
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install fastlane"
        run: "sudo gem install fastlane -NV"

      - name: "Install Dependencies"
        run: "yarn install"

      - name: "Run fastlane command"
        run:  "bundle exec fastlane ios ci_staging"