name: "Fastlane for Staging Environment"

on:
  workflow_dispatch:

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install fastlane"
        run: "sudo gem install fastlane -NV"

  buildApp:
    name: "Build App"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: "Run fastlane command"
        run:  "bundle exec fastlane ios ci_staging"