name: "Fastlane for Custom Environment"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  buildApp:
    name: "Build App"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        if: ${{ github.event.inputs.env == 'dev' || github.event.inputs.env == 'beta' || github.event.inputs.env == 'staging' || github.event.inputs.env == 'release' }}

      - name: "Install fastlane"
        run: "sudo gem install fastlane -NV"
        if: ${{ github.event.inputs.env == 'dev' || github.event.inputs.env == 'beta' || github.event.inputs.env == 'staging' || github.event.inputs.env == 'release' }}

      - name: "Run fastlane command"
        run:  "bundle exec fastlane launch_ci_build env:\"${{ github.event.inputs.env }}\""
        if: ${{ github.event.inputs.env == 'dev' || github.event.inputs.env == 'beta' || github.event.inputs.env == 'staging' || github.event.inputs.env == 'release' }}