name: "Fastlane for Custom Environment"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  setup:
    name: "Setup"
    runs-on: "ubuntu-latest"
    if: ${{ github.event.inputs.env == 'dev' || github.event.inputs.env == 'beta' || github.event.inputs.env == 'staging' || github.event.inputs.env == 'release' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install fastlane"
        run: "sudo gem install fastlane -NV"

  buildApp:
    name: "Build App"
    runs-on: "ubuntu-latest"
    needs: setup
    steps:
      - name: "Run fastlane command"
        run:  "bundle exec fastlane ios ci_${{ github.event.inputs.env }}"