name: "Build iOS and Android App"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  buildApp:
    name: "Build App"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          check-latest: true

      - name: "Install fastlane"
        run: "yarn add fastlane"

      - name: "Run fastlane command"
        run:  "echo \"Run for env: ${{ github.event.inputs.env }}\""