name: "Build iOS and Android App"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  buildApp:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Run for env: ${{ github.event.inputs.env }}"