name: "Upgrade Version"

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type'
        required: true
        default: 'minor'

jobs:
  upgradeVersion:
    name: "Upgrade version"
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Run upgrade command"
        run: "node ./upgrade-version.js ${{ github.event.inputs.type }} ${{ github.event.inputs.version }}"
